DROP TABLE `ai_agents`;--> statement-breakpoint
DROP TABLE `audit_logs`;--> statement-breakpoint
DROP TABLE `automations`;--> statement-breakpoint
DROP TABLE `consents`;--> statement-breakpoint
DROP TABLE `lgpd_requests`;--> statement-breakpoint
DROP TABLE `licenses`;--> statement-breakpoint
DROP TABLE `notification_preferences`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `organization_members`;--> statement-breakpoint
DROP TABLE `organizations`;--> statement-breakpoint
DROP TABLE `payments`;--> statement-breakpoint
DROP TABLE `subscription_plans`;--> statement-breakpoint
DROP TABLE `subscriptions`;--> statement-breakpoint
DROP TABLE `usage_logs`;--> statement-breakpoint
DROP TABLE `whatsapp_accounts`;--> statement-breakpoint
DROP TABLE `whatsapp_conversations`;--> statement-breakpoint
DROP TABLE `whatsapp_integrations`;--> statement-breakpoint
DROP TABLE `whatsapp_messages`;--> statement-breakpoint
DROP TABLE `whatsapp_templates`;--> statement-breakpoint
DROP TABLE `whatsapp_webhooks`;--> statement-breakpoint
ALTER TABLE `contacts` DROP COLUMN `tags`;